GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJhcmkiLCJlbWFpbCI6ImFyaUBnbWFpbC5jb20iLCJpYXQiOjE2NTY0NTc2MTQsImV4cCI6MTY1NjQ1NzYzNH0.9viX6JSekFuoCIcc4P7OLStj4EEtuiui26BGzyF9oKA

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "ari",
    "email": "ari@gmail.com",
    "password": "12345",
    "confPassword": "12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ari@gmail.com",
    "password": "12345"
}

###
GET http://localhost:5000/token
